name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: '1.0.0-preview1'
      packageSource:
        description: 'Package source'
        required: true
        default: 'https://api.nuget.org/v3/index.json'
  push:
    tags:
      - '*'

env:
  Version: ${{ github.event.inputs.releaseVersion }}
  PackageVersion: ${{ github.event.inputs.releaseVersion }}

jobs:
  release_zip:
    needs: verify
    name: Release BaGetter.zip to GitHub
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        global-json-file: global.json
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: |
        dotnet publish src/BaGetter --configuration Release --output artifacts
        tar -czvf bagetter.tar.gz artifacts/
        rm -rf artifacts/*
        mv bagetter.tar.gz artifacts/
        echo ${{ github.sha }} > artifacts/Release.txt
    - name: Upload
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: ${{steps.github_release.outputs.changelog}}
        name: BaGetter
        files: artifacts/**
